name: Docker

# This file is to be removed in the future.

on:
  # pull_request:
  #   branches: ["main"]
  # release:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKERFILE: ./app

jobs:
  Release:

    if: github.event_name != 'pull_request'
    
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write
      pull-requests: write

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Login to Registry
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2.9.0

      -
        name: Extract Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=auto

      -
        name: Build and Push Docker Image
        id: build-and-push
        uses: docker/build-push-action@v4
        if: ${{ github.event_name != 'pull_request' }}
        with:
          platforms: linux/amd64, linux/arm64
          context: ${{ env.DOCKERFILE }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  Scout:
    if: github.event_name == 'pull_request'

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      pull-requests: write

    steps:

      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2.9.0

      -
        name: Extract Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=auto

      -
        name: Build Scout Image
        id: build
        uses: docker/build-push-action@v4
        if: ${{ github.event_name == 'pull_request' }}
        with:
          platforms: linux/amd64
          context: ${{ env.DOCKERFILE }}
          load: true
          # push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      -
        name: Docker Scout
        id: docker-scout
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/scout-action@v0.18.1
        with:
          command: quickview,recommendations,cves
          image: ${{ steps.meta.outputs.tags }}
          only-severities: critical,high
          write-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}