name: Main

on:
  push:
    branches:
      - main
      
permissions:
  pull-requests: write
  
env:
  GH_TOKEN: ${{ github.token }}
      
jobs:
  devPR:
    name: Pull Request to Dev Branch
    
    runs-on: ubuntu-latest
    
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3.5.3
      
      - name: Create Pull Request
        run: |
          ghpr() { gh pr create $* || gh pr edit $*; }
          ghpr --title 'Update Dev with Main' --base 'dev' --head 'main'

