name: Main

on:
  push:
    branches:
      - main
      
permissions:
  pull-requests: write
  
env:
  GH_TOKEN: ${{ github.token }}
  COMMAND: '--title "Update Dev with Main" --body "**Auto PR**" --base "dev" --head "main" --label auto-pr'
      
jobs:
  devPR:
    name: Pull Request to Dev Branch
    
    runs-on: ubuntu-latest
    
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3.5.3
      
      - name: Try to Edit Pull Request
        run: |
          gh pr edit ${{ env.COMMAND }}
      
      - name: Try to Create Pull Request
        if: ${{ failure() }}
        run: |
          gh pr create ${{ env.COMMAND }}
