name: Main

on:
  push:
    branches:
      - main
      
permissions:
  pull-requests: write
  
env:
  GH_TOKEN: ${{ github.token }}
      
jobs:
  devPR:
    name: Pull Request to Dev Branch
    
    runs-on: ubuntu-latest
    
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3.5.3
      
    #  - 
     #   name: Create Pull Request
      #  run: |
       #   gh_pr_up() { gh pr create $* || gh pr edit $* }
        #  gh_pr_up --title "My pull request" --body "Description"
      
      -
        name: PR
        run: gh pr create --title "pr" --body "od" --base "dev" --head "main"
