name: Auto Versioning
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - uses: paulhatch/semantic-version@v5.0.2
          with:
            tag_prefix: ''
            major_pattern: "Major"
            minor_pattern: "Minor"
            version_format: "${major}.${minor}.${patch}-prerelease${increment}"
            # If this is set to true, *every* commit will be treated as a new version.
            bump_each_commit: true
            # The output method used to generate list of users, 'csv' or 'json'.
            user_format_type: "csv"
            # Prevents pre-v1.0.0 version from automatically incrementing the major version.
            # If enabled, when the major version is 0, major releases will be treated as minor and minor as patch. Note that the version_type output is unchanged.
            enable_prerelease_mode: true
